# This defines the resources (request and limits) quota for a given namespace (dev)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev

spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi

# If a resource quota is exceeded for a namespace, then whatever is attempting to deploy at that time will fail and kubernetes will not
# cause any of the quota limits to be exceeded. Kubernetes will reject the deployment and the pods will not be scheduled