# Similar to config maps, require 4 of the same fields
# Data here is manually encoded (typically base64) - But can utilize a vault that gets decrypted in a pipeline on runtime
apiVersion: v1
kind: Secret
metadata:
  name: app-secret

# Commonly utilize a base64 encode here to avoid plain text values
data:
  DB_HOST: bXlzcWw=     # mysql
  DB_USER: cm9vdA==     # root
  DB_PASSWORD: cGFzd3Jk # paswrd